name: 提交文档
description: 提交文档
title: "提交文档-[全英文名称]"
labels: [submit-red-tldr-db]
assignees:
  - rvn0xsy
body:
  - type: textarea
    id: yaml_data
    attributes:
      label: 文档内容
      description: TLDR 文档内容，tags不建议超过3个，注意缩进
      placeholder: "
        name: yum
        tags: [yum]
        data: |
          plateform/linux #target/local  #cat/UTILS 
          
          List all available packages
          ```
          yum list available
          ```"
      value: |
        ```yaml
        name:  yum
        tags: [yum]
        data: |
          plateform/linux #target/local  #cat/UTILS 
          
          List all available packages
          ```
          yum list available
          ```
          
          List all installed packages
          ```
          yum list installed
          ```
        ```
    validations:
      required: true

