name:  Service
tags: [service]
data: |
  
  List services
  ```
  service --status-all
  ```
  
  Status of  a service
  ```
  service <service_name> status
  ```
  
  Start a service
  ```
  service <service_name> start
  ```
  
  Stop a service
  ```
  service <service_name> stop
  ```
  
  Restart a service
  ```
  service <service_name> restart
  ```
  